### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by Yann-J** [xavierchow/metabase-couchbase-driver#1]
Hey there! Many thanks for this work!

Unfortunately I am unable to build the driver, both locally or through Docker.

I'm not very familiar with Clojure so I'm not really able to track this down, none of the few tweaks I've tried have really worked.

```
/app/metabase-cb-driver # lein uberjar
Compiling metabase.driver.couchbase
Syntax error compiling at (metabase/driver/couchbase.clj:79:1).
Syntax error compiling at (metabase/driver/couchbase.clj:79:1).
No such var: driver/substitute-native-parameters
```

I've tried with both the current head and the `v1.0.0` tag...

**Comment by xavierchow** [comment]
@Yann-OAF I will look into the issue soon,
before that, maybe you can build it with the release package as an alternative, see: 
https://github.com/xavierchow/metabase-couchbase-driver#option-2-build-with-release-package

**Comment by Yann-J** [comment]
Yes, indeed I ended up doing that, and the pre-built version seems to work (although I couldn't really test it as I don't have any bucket with a _type attribute)!
This is probably the "right way" to do this kind of thing anyway - this way I can even just download it in a side container and then just map the /plugins volume, no need to use a custom Metabase image.

**Comment by xavierchow** [comment]
Hi @Yann-OAF , I fixed the Dockerfile for building from the source code, but as you mentioned indeed build images with a pre-built version would be much easier and faster.
I'm closing this ticket, feel free to reopen it if you meet any related problems.
