### ISSUE TITLE
Customize the table selection field name

### ISSUE THREAD

**Issue by Yann-J** [xavierchow/metabase-couchbase-driver#2]
Hello!

In our existing buckets we don't have a `_type` field... but we usually do have a `type` field :)

Rather than changing / duplicating that existing field, I'm wondering if it would be possible to make that field name configurable somehow...

Any thoughts?

**Comment by xavierchow** [comment]
it should be doable, let me see how to make it customizable.

**Comment by xavierchow** [comment]
@Yann-OAF  I updated the driver to v1.0.4 to support customizable table selection schema, it might not be an elegant solution but it works.

> schema: it's used to identify which documents belong to this table, it can either a string to present the value of doc._type, or a column separated string defines the doc type. e.g. "schema": "mytype:Ticket"  will select all documents with mytype=Ticket from the bucket.

**Comment by Yann-J** [comment]
Sounds good, many thanks! Will give it a try and report back!

**Comment by xavierchow** [comment]
I'm closing this issue, @Yann-J feel free to reopen if you have further questions.
