### ISSUE TITLE
Some query builder issues

### ISSUE THREAD

**Issue by Yann-J** [xavierchow/metabase-couchbase-driver#5]
Hey there, me again... :)

Your last fix worked great, I can now see some aggregations! Thanks a lot for the nice work 👍 

I have noted a few more issues below, FYI - all seem to related to the query construction.

### All aggregations seem to be `count(*)`

See this query where I'm trying to sum all transactions larger than 10,000 - but the sum looks like a count rather than the real sum.

![image](https://user-images.githubusercontent.com/59641363/121233927-72ff1700-c893-11eb-9602-7c003d9fcdbe.png)

### Cannot display more than one aggregated metric

As soon as I add a metric, I'm getting this error...

![image](https://user-images.githubusercontent.com/59641363/121234029-91651280-c893-11eb-8ae2-137e29e62c52.png)

### Sort does not seem to work

![image](https://user-images.githubusercontent.com/59641363/121234134-ab9ef080-c893-11eb-92c9-0fbcb66236b3.png)

I know it's still a beta of course, so no pressure, just wanted to let you know my findings!

I *think* I'm starting to understand Clojure a little bit, so I *may* be able to send a PR for some of this at some point...

**Comment by xavierchow** [comment]
@Yann-J yeah, you are right, I only implemented the `COUNT` for the summaries(aggregation with a single groupby), so `SUM` won't work as expected.
I will see if I have time in the upcoming weeks, of course, PR is welcomed. :)

**Comment by Yann-J** [comment]
Cool, thanks! Another (unrelated) thing I was wondering about is, if it's possible to query via the Couchbase Analytics service rather than the query service... I see that the couchbase library used in the driver seems a little old, and I suspect it doesn't support this...

**Comment by xavierchow** [comment]
@Yann-J 
I implemented the SUM aggregation(as multiple metrics with COUNT) in https://github.com/xavierchow/metabase-couchbase-driver/releases/tag/v1.0.8.
Please have a try and let me know if there is any issue.

**Comment by Yann-J** [comment]
Working great for me so far, thanks for that!

**Comment by xavierchow** [comment]
cool, I'm closing this issue then.
